behaviors:
  GhostAgent:
    trainer_type: ppo
    hyperparameters:
      batch_size: 128
      buffer_size: 2048
      learning_rate: 0.0003
      beta: 0.005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 256
      num_layers: 2
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    keep_checkpoints: 5
    max_steps: 20000000
    time_horizon: 128
    summary_freq: 10000
    threaded: true
environment_parameters:
  player_speed:
    curriculum:
      - name: Lesson0
        completion_criteria:
          measure: reward
          behavior: GhostAgent
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 0.8
        value:
          sampler_type: uniform
          sampler_parameters:
            min_value: 0.0
            max_value: 0.2
      - name: Lesson1
        completion_criteria:
          measure: reward
          behavior: GhostAgent
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 0.8
        value:
          sampler_type: uniform
          sampler_parameters:
            min_value: 0.2
            max_value: 0.6
      - name: Lesson2
        completion_criteria:
          measure: reward
          behavior: GhostAgent
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 0.8
        value:
          sampler_type: uniform
          sampler_parameters:
            min_value: 0.6
            max_value: 1.0