behaviors:
  GhostAgent:
    trainer_type: ppo
    hyperparameters:
      batch_size: 10
      buffer_size: 100
      learning_rate: 3.0e-4
      beta: 5.0e-4
      epsilon: 0.1
      lambd: 0.99
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 256
      num_layers: 2
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    max_steps: 10000000
    time_horizon: 64
    summary_freq: 2000
    
environment parameters:
  my_environment_paramter:
    curriculum:
      - name: FirstLesson
        completion_criteria:
          measure: reward
          signal_smoothing: true
          min_lesson_length: 10
          threshold: .5
        value: 0.0
      - name: SecondLesson
        completion_criteria:
          measure: reward
          signal_smoothing: true
          min_lesson_length: 10
          threshold: .5
        value:
            sampler_type: uniform
            sampler_parameters:
                min_value: 4.0
                max_value: 8.0
      -name: LastLesson
        value: 8